---
# tasks file for helabs.memcached
- name: Installing memcached packages
  yum:
    name: "{{ item }}"
    state: present
  with_items: memcached_redhat_pkgs
  when: ansible_os_family == "RedHat"

- name: Installing memcached packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: memcached_debian_pkgs
  when: ansible_os_family == "Debian"

- name: Templating out client configuration file
  template:
    src: memcached_redhat.j2
    dest: /etc/sysconfig/memcached
  notify:
   - restart memcached
  when: ansible_os_family == "RedHat"

- name: Templating out client configuration file
  template:
    src: memcached_debian.j2
    dest: /etc/memcached.conf
  notify: restart memcached
  when: ansible_os_family == "Debian"

- name: Setting max open file descriptors
  sysctl:
    name: fs.file-max
    value: "{{ memcached_fs_file_max }}"
    state: present
    ignoreerrors: yes
  notify:
    - start memcached
